
# SEO settings
title: "Kwap Consulting Piotr Kwapin"
title2: "" # default: ""
description: "I work with employees, managers, and teams to help them reach their full potential."
keywords: "tech, thinking, books"
url: https://kwap.io #kwap.github.io/kwap # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: https://github.com/kwap/kwap.github.io
disqus_shortname: "geekbeing"
twitter_username: "o3tker"
comments: false

# Build settings
permalink   : /:year-:month-:day/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Piotr Kwapin"
  job      : "Lead Consultant at Kwap Consulting"
  bio      : "</br> Get in touch with me via <a href='http://linkedin.com/in/piotrkwapin'>LinkedIn</a> or drop me an email at <a href='mailto:piotr.kwapin@gmail.com'>piotr.kwapin@gmail.com</a>"
  thumb    : "https://en.gravatar.com/userimage/6180910/ba6df19995b5a4fd3adfd54cae8b0bec.jpeg?size=200"
  email    : piotr.kwapin@gmail.com
  url      : https://kwap.io
  github   : http://github.com/kwap
  twitter  : http://twitter.com/o3tker
  linkedin : http://linkedin.com/in/piotrkwapin

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@o3tker"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]

theme: jekyll-theme-minimal